### ISSUE TITLE
PutAttributes missing Attributes error

### ISSUE THREAD

**Issue by benconnito** [aws/aws-sdk-php-v3-bridge#1]
Error executing "PutAttributes" on "https://sdb.amazonaws.com"; AWS HTTP error: Client error: 400 MissingParameter (client): No attributes - MissingParameterNo attributes0.00002199072403a8cc-9bd7-4843-9673-e0b4a6a7fb86

Yet im sending:

$this->client->putAttributes(array(
      'DomainName' => 'mytable',
      'ItemName' => 'mykey',
      'Attributes' => $item['Attributes']
    ));

and $item['Attributes'] looks like this:

json -

```
[{"Name":"data","Value":"","Replace":true},{"Name":"modified","Value":"1444068041","Replace":true}]
```

php - 

```
Array
(
    [0] => Array
        (
            [Name] => data
            [Value] => 
            [Replace] => 1
        )

    [1] => Array
        (
            [Name] => modified
            [Value] => 1444067975
            [Replace] => 1
        )

)
```

**Comment by jeskew** [comment]
Thanks for reporting. I should have a fix out quickly.

**Comment by jeskew** [comment]
Upgrading to 0.1.0 should take care of this. Let me know if you run into anything else.
