### ISSUE TITLE
Value is required where it should not.

### ISSUE THREAD

**Issue by rjimeno** [aws/aws-sdk-php-v3-bridge#5]
When I call deleteAttributes() I get the error:

Unable to delete attribute 'create_domain.php: Found 1 error while validating the input provided for the DeleteAttributes operation:
[Attributes][0][Value] is missing and is a required parameter

Even though 'Value' is not required as part of Attributes (well, that's my interpretation of the documentation I found [here](https://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.SimpleDb.SimpleDbClient.html#_deleteAttributes) and [here](https://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-simpledb.html) as well as examples from old books for v1).

I do believe this was fixed in v2 as it was reported and noted [here](https://github.com/aws/aws-sdk-php/issues/185), but maybe the bug was re-introduced later.

It is my believe that, without a specific Value, deleteAttributess() should get rid of all the attributes for each Name given inside Attributes.

The attached file is the one where I observed the problem. Note that my comment near line 23.
[delete_attrs.php.gz](https://github.com/aws/aws-sdk-php-v3-bridge/files/1671423/delete_attrs.php.gz)

**Comment by ajredniwja** [comment]
Is this still a persisting issue?

**Comment by rjimeno** [comment]
It probably is, but it does not matter anymore; it's been 3 years since I requested help and, by then, the problem was already old.

For sure there's a new and better way to accomplish what I wanted then. Thanks for reaching out though!
